### PR TITLE
Update Ember

### PR DESCRIPTION
**Pull request by donaldwasserman**
Update ember packages to 2.18

I closed #5 in lieu of this and make a subsequent PR with the additional functionality @HeroicEric

### CODE REVIEW

**Comment by donaldwasserman** [comment]
@HeroicEric I updated this. I can't figure out why #7 still has randomly failing phantom tests (my phantom won't even load tests locally at the moment), but all the tests are green on chrome. 

What's your feeling about getting some of this wrapped up?

**Comment by alechirsch** [comment]
+1 please, this fixes a deprecation

**Comment by crhayes** [comment]
@donaldwasserman @HeroicEric Any update on this? This library is causing a deprecation warning unfortunately 

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: goodtalk-web-client -> ember-full-story -> ember-cli-babel
```

**Comment by HeroicEric** [comment]
@crhayes I'll make some time for this today. Thank you for pinging me! 😄

**Comment by crhayes** [comment]
@HeroicEric Thanks for the quick response, appreciate it!

**Comment by donaldwasserman** [comment]
Hello - I was using this for a specific work project and somewhat forgot the details (we were using a private fork IIRC)

I'd be happy to revisit this if need be and go back and get off my private fork.

**Comment by HeroicEric** [comment]
@donaldwasserman thanks for the help! Sorry for not following up sooner. I updated to a newer version of ember and ember-cli here https://github.com/HeroicEric/ember-full-story/pull/9

**Pull request closed without merging**
