### PR TITLE
Update ember-cli & ember to v3.6.0

### PR DESCRIPTION
**Pull request by HeroicEric**
Fixes https://github.com/HeroicEric/ember-full-story/issues/8

Updates ember-cli & ember to v3.6.0.

This also adds a `yarn.lock` file.

### CODE REVIEW

**Comment by crhayes** [comment]
💯!!

**Comment by crhayes** [comment]
@HeroicEric Would you mind tagging a release of this and releasing on npm?

**Comment by HeroicEric** [comment]
@crhayes just pushed a new release

**Comment by crhayes** [comment]
@HeroicEric 🙏🙏🙏

**Pull request merged**
